package App;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pakorns หลักสูตรวิทยาการคอมพิวเตอร์ วันที่ 1 มกราคม 2565 วิชา
 * การเขียนโปรแกรมเชิงวัตถุ
 */
public class MainFrame extends javax.swing.JFrame {

    public static Connection conn=null;
    public static final String URL = "jdbc:mysql://localhost:3306/db_example";
    public static final String USER = "root";
    public static final String PASSWORD = "pk123456";
    public static Statement sqlStatement=null;
    public static ResultSet rs=null;
    public static DefaultTableModel defaultTablemodel=null;
    public static PreparedStatement ps=null;
    int id;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
      updateDB();

    }

    public void connectdb() {
        try {
            //เชื่อมฐานข้อมูล
            conn = DriverManager.getConnection(URL, USER, PASSWORD);
            //สร้างสเตตเมนต์สำหรับคำสั่ง sql 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ไม่สามารถเปิดฐานข้อมูลได้", "แจ้งเตือน",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jUpdate = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        jShowUser = new javax.swing.JButton();
        jUserName = new javax.swing.JTextField();
        jPasswd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAddress = new javax.swing.JTextArea();
        jReset = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableuser = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLayeredPane2.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 4));
        jLayeredPane2.setOpaque(true);

        jLayeredPane1.setBackground(new java.awt.Color(51, 255, 153));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 6));
        jLayeredPane1.setOpaque(true);

        jUpdate.setText("Update");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        jSave.setText("Add new");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jShowUser.setText("Show");
        jShowUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowUserActionPerformed(evt);
            }
        });

        jUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jUserNameKeyPressed(evt);
            }
        });

        jPasswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswdKeyPressed(evt);
            }
        });

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        jLabel3.setText("Address");

        jLabel4.setText("E-Mail");

        jAddress.setColumns(20);
        jAddress.setRows(5);
        jScrollPane2.setViewportView(jAddress);

        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jShowUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jUserName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPasswd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jReset, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jExit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jUserName)
                        .addGap(24, 24, 24))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jPasswd)
                        .addGap(245, 245, 245))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jEmail)
                        .addContainerGap())
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jShowUser)
                        .addGap(37, 37, 37)
                        .addComponent(jSave)
                        .addGap(45, 45, 45)
                        .addComponent(jUpdate)
                        .addGap(38, 38, 38)
                        .addComponent(jReset)
                        .addGap(38, 38, 38)
                        .addComponent(jDelete)
                        .addGap(28, 28, 28)
                        .addComponent(jExit)
                        .addContainerGap(83, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jShowUser)
                    .addComponent(jSave)
                    .addComponent(jUpdate)
                    .addComponent(jExit)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jReset)
                        .addComponent(jDelete)))
                .addGap(40, 40, 40))
        );

        tableuser.setBackground(new java.awt.Color(204, 204, 255));
        tableuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "id", "User", "Password", "Email", "Address"
            }
        ));
        tableuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableuserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableuser);

        jLayeredPane2.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jLayeredPane1)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jShowUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowUserActionPerformed
        //fetch();
        updateDB();
    }//GEN-LAST:event_jShowUserActionPerformed
    public final void fetch() {
        try {
            connectdb();
            //สร้างสเตตเมนต์สำหรับคำสั่ง sql 
            String sql = "Select * from users";
            sqlStatement = conn.createStatement();
            rs = sqlStatement.executeQuery(sql);
            defaultTablemodel = (DefaultTableModel) tableuser.getModel();
            defaultTablemodel.setRowCount(0);
            while (rs.next()) {
                Object obj[] = {rs.getInt("id"),
                    rs.getString("user_name"),
                    rs.getString("user_password"),
                    rs.getString("email"),
                    rs.getString("address")};
                defaultTablemodel.addRow(obj);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "ไม่สามารถเปิดฐานข้อมูลได้", "แจ้งเตือน",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        if (!jUserName.getText().isEmpty() && !jPasswd.getText().isEmpty()) {
            try {
                //เชื่อมฐานข้อมูล
                connectdb();
                //เพิ่มข้อมูลใหม่

                String sql = "INSERT INTO users(user_name,user_password,email,address) value(?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, jUserName.getText());
                ps.setString(2, jPasswd.getText());
                ps.setString(3, jEmail.getText());
                ps.setString(4, jAddress.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,
                        "บันทึกเรียบร้อย", "แจ้งเตือน",
                        JOptionPane.INFORMATION_MESSAGE);
               fetch();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "ไม่สามารถเปิดฐานข้อมูลได้", "แจ้งเตือน",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "กรุณากรอกข้อมูลให้ครบ", "ข้อผิดพลาด !",
                    JOptionPane.ERROR_MESSAGE);
            jUserName.requestFocus(); //
        }
    }//GEN-LAST:event_jSaveActionPerformed

    private void jUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUserNameKeyPressed
        if (evt.getKeyCode() == 10) {
            jPasswd.requestFocus();
        }
    }//GEN-LAST:event_jUserNameKeyPressed

    private void jPasswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswdKeyPressed
        if (evt.getKeyCode() == 38) { //38=keyup
            jUserName.requestFocus();
        }
    }//GEN-LAST:event_jPasswdKeyPressed
    private JFrame formExit;
    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        formExit = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(formExit, "Are you shure to exit [yes/no]", "Confirm to Exit",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_jExitActionPerformed

    private void tableuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableuserMouseClicked
        DefaultTableModel recordTable = (DefaultTableModel) tableuser.getModel();
        int rowSelected = tableuser.getSelectedRow();
        id = Integer.parseInt(recordTable.getValueAt(rowSelected,0).toString());
        jUserName.setText(recordTable.getValueAt(rowSelected, 1).toString());
        jPasswd.setText(recordTable.getValueAt(rowSelected, 2).toString());
        jEmail.setText(recordTable.getValueAt(rowSelected, 3).toString());
        jAddress.setText(recordTable.getValueAt(rowSelected, 4).toString());
    }//GEN-LAST:event_tableuserMouseClicked

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        if (!jUserName.getText().isEmpty() && !jPasswd.getText().isEmpty()) {
            try {
                //เชื่อมฐานข้อมูล
                connectdb();
                //เพิ่มข้อมูลใหม่
                

                String sql = "UPDATE users SET user_name =?, user_password =?, email =?, address =? where id=?";
               
                ps = conn.prepareStatement(sql);
                ps.setString(1, jUserName.getText());
                ps.setString(2, jPasswd.getText());
                ps.setString(3, jEmail.getText());
                ps.setString(4, jAddress.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"บันทึกเรียบร้อย", "แจ้งเตือน",JOptionPane.INFORMATION_MESSAGE);
                updateDB();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"ไม่สามารถเปิดฐานข้อมูลได้", "แจ้งเตือน",JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "กรุณากรอกข้อมูลให้ครบ", "ข้อผิดพลาด !", JOptionPane.ERROR_MESSAGE);
            jUserName.requestFocus(); //
        }
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        jUserName.setText("");
        jPasswd.setText("");
        jEmail.setText("");
        jAddress.setText("");
        
    }//GEN-LAST:event_jResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }
//=========Functions==============

    

    public void updateDB() {
        try {
            
            connectdb();
            String sql = "Select * from users";
             
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData resultSet = rs.getMetaData();
            int columnCount =resultSet.getColumnCount();
            defaultTablemodel = (DefaultTableModel) tableuser.getModel();
            defaultTablemodel.setRowCount(0);
            while (rs.next()) {
                Vector selectRow = new Vector();
                for(int i =0; i<=columnCount;i++){
                       selectRow.add(rs.getString("id"));
                       selectRow.add(rs.getString("user_name"));
                       selectRow.add(rs.getString("user_password"));
                       selectRow.add(rs.getString("email"));
                       selectRow.add(rs.getString("address"));
                }
                defaultTablemodel.addRow(selectRow);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "ไม่สามารถเปิดฐานข้อมูลได้", "แจ้งเตือน",
                    JOptionPane.INFORMATION_MESSAGE);
        }

     
    }

   

//=========end functins============
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAddress;
    private javax.swing.JButton jDelete;
    private javax.swing.JTextField jEmail;
    private javax.swing.JButton jExit;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTextField jPasswd;
    private javax.swing.JButton jReset;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jShowUser;
    private javax.swing.JButton jUpdate;
    private javax.swing.JTextField jUserName;
    private javax.swing.JTable tableuser;
    // End of variables declaration//GEN-END:variables
}
